-- 특정 유저 상점 조회
SELECT USER_NO, SHOP_TITLE, SHOP_INFO
FROM "shop"
JOIN "users" USING(USER_NO)
WHERE USER_NO = 1;


-- 특정 유저 게시글 목록 조회
SELECT USER_NO, CATEGORY_NO, GOODS_TITLE, GOODS_DESCR, GOODS_PRICE, 
		VIEW_COUNT, WISH_COUNT, SELL_ENROLL_DT, GOODS_STATUS
FROM "goods_board"
WHERE USER_NO = 1;

-- 날짜 계산
SELECT TRUNC(SYSDATE-ENROLL_DT) OPEN_DAY
FROM "users"
WHERE USER_NO = 1;


-- 특정 회원 팔로워 리스트
SELECT FOLLOWING_USER_NO, SHOP_TITLE, SHOP_INFO, U.USER_IMG 
FROM "follow" F
JOIN "users" U ON(U.USER_NO = F.USER_NO)
JOIN "shop" S ON(FOLLOWING_USER_NO = S.USER_NO)
WHERE F.USER_NO = 1;


-- 특정 상점 팔로잉 리스트
SELECT F.USER_NO USER_NO, SHOP_TITLE, SHOP_INFO, U.USER_IMG
FROM "follow" F
JOIN "users" U ON(U.USER_NO = F.USER_NO)
JOIN "shop" S ON(U.USER_NO = S.USER_NO) 
WHERE FOLLOWING_USER_NO = 6;

-- 특정 유저(상점) 거래 후기 조회
SELECT REVIEW_NO, SHOP_TITLE, GOODS_NO, REVIEW_MESSAGE,
		REVIEW_DT, REVIEW_STARS
FROM "reviews" R
JOIN "users" USING(USER_NO)
JOIN "shop" USING(USER_NO)
JOIN "goods_board" B USING(GOODS_NO)
WHERE REVIEW_DEL_FL = 'N'
AND B.USER_NO = 1;
